CREATE DATABASE centro_de_distribuicao_data_base; /**COMANDO PARA CRIAR A BASE DE DADOS**/
DROP DATABASE centro_de_distribuicao_data_base; /** COMANDO PARA EXCLUIR A BASE DE DADOS**/
CREATE DATABASE centro_de_distribuicao; /**COMANDO PARA CRIAR A BASE DE DADOS**/
USE centro_de_distribuicao; /**COMANDO PARA USAR O BANCO DE DADOS CRIADO*/
DROP DATABASE IF EXISTS centro_de_distribuicao; /**COMANDO CASO EXISTA A BASE DE DADOS EXCLUI.**/

CREATE DATABASE jeanMoraes;
USE  jeanMoraes;
/**PARA CRIAR A TABELA SEMPRE TER PELO MENOS UMA COLUNA E USAR OS PARENTESES PARA ABRIR E FECHAR A TABELA**/
CREATE TABLE estado ( 
id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT
, nome VARCHAR (100) NOT NULL 
, sigla CHAR (2)  
);
